version: 2

sources:
  - name: tpch_sample
    schema: TPCH_SF001
    database: RAW
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
